config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/search'
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :search_product, only: [:index, :search]

  def index
    @tags = Tag.all
    @items = @p.result.includes(:user, :tags)
  end

  def search
    @p = Item.search(search_params)
    @items = @p.result.includes(:user, :tags)
  end

  private

  def search_product
    @p = Item.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def search_params
     params.require(:q).permit(:name_cont, :price_lteq, :category_id_eq, :sales_status_id_eq, :shipping_fee_status_id_eq, :scheduled_delivery_id_eq, :tags_id_eq)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render "shared/header" %> 
<div class="items-search-contents">
  <div class="items-search-main">
    <h1 class="items-sell-title">商品検索</h1>
    <%= search_form_for @p, url: products_search_path do |f| %>
      <div class="new-items">
        <div class="weight-bold-text">
          <%= f.label :name_cont, '商品名' %>
        </div>
        <%= f.search_field :name_cont, class:"items-search-text", placeholder:"商品名に含まれている文字を検索"%>
      </div>
      <div class="weight-bold-text">
        <%= f.label :price, '価格帯' %>
      </div>
      <%= f.radio_button :price_lteq, '' %>
      指定なし
      <%= f.radio_button :price_lteq, '1000' %>
      1000円以下
      <%= f.radio_button :price_lteq, '2500' %>
      2500円以下
      <%= f.radio_button :price_lteq, '5000' %>
      5000円以下
      <br>
      <div class="items-search-form">
        <div class="weight-bold-text">
        <%= f.label :category_id_eq,'カテゴリー' %> 
        </div>
        <div class="search-select-box">
        <%= f.collection_select :category_id_eq, Category.find([2,3,4,5,6,7,8,9,10,11]), :id, :name, include_blank: '指定なし' %> 
        </div>
      </div>
      <div class="items-search-form">
        <div class="weight-bold-text">
        <%= f.label :sales_status_id_eq,'商品の状態' %>
        </div> 
        <div class="search-select-box">
        <%= f.collection_select :sales_status_id_eq, SalesStatus.find([2,3,4,5,6,7]), :id, :name, include_blank: '指定なし' %> 
        </div>
      </div>
      <div class="items-search-form">
        <div class="weight-bold-text">
        <%= f.label :shipping_fee_status_id_eq,'配送料の負担' %>
        </div> 
        <div class="search-select-box">
        <%= f.collection_select :shipping_fee_status_id_eq, ShippingFeeStatus.find([2,3]), :id, :name, include_blank: '指定なし' %> 
        </div>
      </div>
      <div class="items-search-form">
        <div class="weight-bold-text">
        <%= f.label :scheduled_delivery_id_eq,'発送までの日数' %>
        </div> 
        <div class="search-select-box">
        <%= f.collection_select :scheduled_delivery_id_eq, ScheduledDelivery.find([2,3,4]), :id, :name, include_blank: '指定なし' %> 
        </div>
      </div>
      <div class="items-search-form">
        <div class="weight-bold-text">
        <%= f.label :tags_id_eq,'タグ' %>
        </div> 
        <div class="search-select-box">
        <%= f.collection_select :tags_id_eq, @tags, :id, :tag_name, include_blank: '指定なし' %> 
        </div>
      </div>
      <%= f.submit '検索' %>
      <br>
  
    <% end %>
  </div>
</div>

app/views/products/search.html.erb
<%= render "shared/header" %> 
<div class="items-search-contents">
<h1 class="items-sell-title">検索結果</h1>
<ul class='item-lists'>
  <% if @items.length !=0 %>
    <% @items.each do |result| %>
      <td>
      <br>
        <% if result.record.present? %>
        <% else %>
          <li class='search-list'>
            <%= link_to item_path(result) do %>
            <div class='item-img-content'>
              <%= image_tag result.image, class: "search-item-img" %>
              <% if result.record.present? %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
              <% end %>
            </div>

          <div class='item-info'>
            <h3 class='item-name'>
              <%= result.name %>
            </h3>
              <div class='item-price'>
                <span><%= result.price %>円<br>
                <%= result.category.name %><br>
                <%= result.sales_status.name %><br>
                <%= result.scheduled_delivery.name %><br>
                <%= result.shipping_fee_status.name %><br>
                <%= result.tags.pluck(:tag_name) %>
                </span>
              </div>
            </div>
            <% end %>
          </li>
        <% end %>
    <% end %>
  <% else %>
    該当する商品はありません
  <% end %>
</ul>
<br> 
<%= link_to 'トップページへ戻る', root_path %>
</div>